- type: job
  id: AtmosphericTechnician
  name: job-name-atmostech
  description: job-description-atmostech
  playTimeTracker: JobAtmosphericTechnician
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 36000 # 15 hrs
  startingGear: AtmosphericTechnicianGear
  icon: "JobIconAtmosphericTechnician"
  supervisors: job-supervisors-ce
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics
  alternateTitles:
  - AtmosTitleLifeSupport
  - AtmosTitleSupervisor
  - AtmosTitleOperator
  - AtmosTitleFireman

- type: startingGear
  id: AtmosphericTechnicianGear
  equipment:
    eyes: ClothingEyesGlassesMeson
    id: AtmosPDA
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering
  #storage:
    #back:
    #- Stuff

- type: jobAlternateTitle
  id: AtmosTitleLifeSupport
  name: job-name-alt-atmos-life-support

- type: jobAlternateTitle
  id: AtmosTitleSupervisor
  name: job-name-alt-atmos-supervisor

- type: jobAlternateTitle
  id: AtmosTitleOperator
  name: job-name-alt-atmos-operator

- type: jobAlternateTitle
  id: AtmosTitleFireman
  name: job-name-alt-atmos-fireman
