- type: job # goob edit
  id: Passenger
  name: job-name-passenger
  description: job-description-passenger
  playTimeTracker: JobPassenger
  startingGear: PassengerGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-everyone
  alternateTitles:
  - AssistantTitlePassenger
  - AssistantTitleOffDuty
  - AssistantTitleFreelancer
  - AssistantTitleErrand
  - AssistantTitleTrader
  - AssistantTitleTourist
  - AssistantTitleIntern
  - AssistantTitleTest
  - AssistantTitleArtist

- type: startingGear
  id: PassengerGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey
  #storage:
    #back:
    #- Stuff

- type: jobAlternateTitle
  id: AssistantTitlePassenger
  name: job-name-alt-assistant-passenger

- type: jobAlternateTitle
  id: AssistantTitleOffDuty
  name: job-name-alt-assistant-off-duty

- type: jobAlternateTitle
  id: AssistantTitleFreelancer
  name: job-name-alt-assistant-freelancer

- type: jobAlternateTitle
  id: AssistantTitleErrand
  name: job-name-alt-assistant-errand

- type: jobAlternateTitle
  id: AssistantTitleTrader
  name: job-name-alt-assistant-trader

- type: jobAlternateTitle
  id: AssistantTitleTourist
  name: job-name-alt-assistant-tourist

- type: jobAlternateTitle
  id: AssistantTitleIntern
  name: job-name-alt-assistant-intern

- type: jobAlternateTitle
  id: AssistantTitleTest
  name: job-name-alt-assistant-test

- type: jobAlternateTitle
  id: AssistantTitleArtist
  name: job-name-alt-assistant-artist
