- type: job
  id: Bartender
  name: job-name-bartender
  description: job-description-bartender
  playTimeTracker: JobBartender
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 1800 # 30 Minutes
  startingGear: BartenderGear
  icon: "JobIconBartender"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  - Bar
  extendedAccess:
  - Kitchen
  - Hydroponics
  alternateTitles:
  - BartenderTitleMixologist
  - BartenderTitleBarman
  - BartenderTitleBarwoman

- type: startingGear
  id: BartenderGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: BartenderPDA
    ears: ClothingHeadsetService
  #storage:
    #back:
    #- Stuff

- type: jobAlternateTitle
  id: BartenderTitleMixologist
  name: job-name-alt-bartender-mixologist

- type: jobAlternateTitle
  id: BartenderTitleBarman
  name: job-name-alt-bartender-barman

- type: jobAlternateTitle
  id: BartenderTitleBarwoman
  name: job-name-alt-bartender-barwoman
