- type: job
  id: Chef
  name: job-name-chef
  description: job-description-chef
  playTimeTracker: JobChef
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 1800 # 30 Minutes
  startingGear: ChefGear
  icon: "JobIconChef"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  - Kitchen
  extendedAccess:
  - Hydroponics
  - Bar
  alternateTitles:
  - ChefTitleSteward
  - ChefTitleCook
  - ChefTitlePizza

- type: startingGear
  id: ChefGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: ChefPDA
    ears: ClothingHeadsetService
    belt: ClothingBeltChefFilled
  #storage:
    #back:
    #- Stuff

- type: jobAlternateTitle
  id: ChefTitleSteward
  name: job-name-alt-chef-steward

- type: jobAlternateTitle
  id: ChefTitleCook
  name: job-name-alt-chef-cook

- type: jobAlternateTitle
  id: ChefTitlePizza
  name: job-name-alt-chef-pizza
